spring:
  application:
    name: progress-document
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_PROGRESS_DOCUMENT:progress-document}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    initialize: true
    maxActive: 3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: ./logs/log-file.log
springdoc:
  packagesToScan:  com.github.amorixa.progressdocument.controller
  swagger-ui:
    path: /docs-translate-progress.html
  api-docs:
    path: /docs-translate-progress